export type PostBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "code"; code: string }
  | { type: "img"; src: string; alt: string }
  | { type: "quote"; text: string };

export type Post = {
  slug: string;
  title: string;
  date: string;
  readTime: string;
  summary: string;
  cover: string;
  coverAlt: string;
  blocks: PostBlock[];
};

export const posts: Post[] = [
  {
    slug: "first-lms-system",
    title: "Learning Co-Pilot",
    date: "2025-07-01",
    readTime: "2 min read",
    summary:
      "A custom learning management system for K-12 robotics instruction — an animated robot with responsive eyes, a nano-bot team system, and an evolving AI copilot watching student performance.",
    cover: "/images/robot.png",
    coverAlt: "Animated robot character from the Learning Co-Pilot LMS",
    blocks: [
      {
        type: "p",
        text: "It started as a simple point-tracking system that let students earn points, power up their robots, and attack the monster — the main goal of each in-person class. Over time, the more features I added, the more this system took on shape and personality.",
      },
      {
        type: "p",
        text: "The story is that each student controls one nano-bot (located on the teeth of the robot), and the goal is to defeat the virus. The entire main processing frame must be saved.",
      },
      { type: "img", src: "/images/lms2.png", alt: "Learning Co-Pilot class dashboard" },
      { type: "h2", text: "From point tracker to co-pilot" },
      {
        type: "p",
        text: "What began as gamified scorekeeping evolved into a real learning management system: an animated robot character with responsive eyes that reacts to the class, a nano-bot system that gives every student an agent to control, and an AI copilot layer that monitors how students are progressing so I could adapt the lesson in real time.",
      },
      { type: "img", src: "/images/lms3.png", alt: "Nano-bot team view in the LMS" },
      {
        type: "p",
        text: "The biggest lesson: kids don't engage with software because it's educational. They engage because it has stakes, characters, and a story. The pedagogy hides inside the game.",
      },
      { type: "img", src: "/images/lms5.png", alt: "Student progress view in the LMS" },
      {
        type: "quote",
        text: "I just wanted my students to feel jazzed about going to coding class and feel a sense of teamwork and camaraderie.",
      },
    ],
  },
  {
    slug: "hack-fy2025",
    title: "Microsoft AI Agents Hackathon FY2025",
    date: "2025-07-01",
    readTime: "2 min read",
    summary:
      "Shipping Data Forge Lite to the Microsoft Reactor Hackathon — an AI-powered data storytelling app, up against 500+ projects from across the nation.",
    cover: "/images/hacker.png",
    coverAlt: "Illustration of a developer at a terminal",
    blocks: [
      {
        type: "p",
        text: "The Microsoft Reactor Hackathon FY2025 was my first official competition against other individual developers and teams of up to four. I got to see some seriously impressive submissions — with over 500 notable projects, I was up against some of the best in the nation.",
      },
      {
        type: "p",
        text: "I submitted Data Forge Lite, a Streamlit app that lets non-technical users upload any dataset under 200MB. The application takes the user from data ingestion, to interactive mind mapping, to data visualization and storytelling.",
      },
      { type: "img", src: "/images/heatmap.png", alt: "Interactive heatmap generated by Data Forge Lite" },
      { type: "h2", text: "What Data Forge actually does" },
      {
        type: "p",
        text: "Under the hood it's an agent-based conversation interface with careful prompt engineering driving Plotly visualizations. You talk to your dataset; it answers with charts. The mind-mapping stage helps users discover what questions are even worth asking before they start plotting.",
      },
      { type: "img", src: "/images/hacka.jpeg", alt: "Hackathon event" },
      {
        type: "p",
        text: "Competing taught me more than building alone ever has: scoping ruthlessly, demoing clearly, and accepting that a feature that can't be shown in ninety seconds may as well not exist.",
      },
    ],
  },
  {
    slug: "jupyter-kernel-setup",
    title: "VENV and Jupyter Notebook Kernel Playbook",
    date: "2025-06-13",
    readTime: "5 min read",
    summary:
      "Matching virtual environments with Jupyter kernels for AI agent development — the foundational step that keeps LangChain, Streamlit, and OpenAI workflows from failing silently.",
    cover: "/images/popcorn.png",
    coverAlt: "Popcorn illustration from the Jupyter kernel playbook",
    blocks: [
      {
        type: "p",
        text: "Without this foundational step of connecting your venv with an interactive Jupyter notebook kernel, AI agents built with frameworks like LangChain, Streamlit, and OpenAI often fail silently or misbehave. You need consistency between the environment you develop in and the one your notebook executes in.",
      },
      {
        type: "p",
        text: "When you're building autonomous agents that rely on APIs, vector stores, or chained reasoning, reproducibility becomes key. Registering your virtual environment as a Jupyter kernel ensures your notebooks run exactly the way your backend code does — same dependencies, same execution context, no surprises.",
      },
      { type: "h2", text: "The playbook" },
      {
        type: "code",
        code: `# 1. Create a virtual environment (if you haven't already)
python3 -m venv venv

# 2. Activate the virtual environment
source venv/bin/activate

# 3. Install required packages (optional)
pip install -r requirements.txt

# 4. Install Jupyter kernel support inside the venv
pip install ipykernel

# 5. Register the venv as a Jupyter kernel
python -m ipykernel install --user --name=venv --display-name "Python (venv)"

# 6. Launch VS Code and open your notebook
code .

# 7. Select the "Python (venv)" kernel in the top-right dropdown

# 8. Press Shift+Enter to execute notebook cells`,
      },
      {
        type: "p",
        text: "That's the whole trick. Eight steps, two minutes, and every notebook in the project now executes against the exact dependency set your Flask app, your vector store client, and your agent code use.",
      },
      { type: "quote", text: "Set your environment right, and the agent will follow." },
      { type: "p", text: "Don't just run notebooks. Align them with your tools. 🔧" },
    ],
  },
  {
    slug: "rhombus-systems",
    title: "Anaheim School District Hour of Code",
    date: "2025-07-01",
    readTime: "2 min read",
    summary:
      "Teaching 200+ middle school students IoT development through a Mars Habitat build — Raspberry Pi, Arduino, ultrasonic sensors, and four specialized student teams.",
    cover: "/images/dome.png",
    coverAlt: "Illustration of a Mars habitat dome",
    blocks: [
      {
        type: "p",
        text: "As the adjunct instructor for the Anaheim School District, my goal was to deliver the Hour of Code curriculum to over 200 middle school students. The theme for this year's IoT development course: build a Mars Habitat and landing site with smart-city features, sensors, and motors. Our hardware stack included Raspberry Pi, Arduino, and Chromebooks for wireless SSH.",
      },
      {
        type: "p",
        text: "Our team was in charge of the Anaheim School District — Ponderosa, Jefferson, and Stoddard Elementary — with the goal of having the entire 6th–8th grade class produce ten IoT projects using resources provided to non-profit STEM organizations.",
      },
      { type: "img", src: "/images/teacher2.jpg", alt: "Lannon teaching a robotics class" },
      { type: "h2", text: "Four teams, one habitat" },
      {
        type: "p",
        text: "Students split into specializations — chassis, software, electronics, and sensors — and had to integrate their work, just like a real engineering org. The rovers navigated autonomously using ultrasonic sensors; the habitat's smart-city features ran on the same boards the students wired themselves.",
      },
      { type: "img", src: "/images/jeff.jpeg", alt: "Students building their IoT project" },
      {
        type: "p",
        text: "Watching a 6th grader debug a sensor wiring problem on their own — because the rover they care about won't turn — is the entire argument for project-based learning in one image.",
      },
      { type: "img", src: "/images/boop.jpeg", alt: "Student robotics build in progress" },
      {
        type: "quote",
        text: "I just wanted my students to feel jazzed about going to coding class and feel a sense of teamwork and camaraderie.",
      },
    ],
  },
];

export function getPost(slug: string): Post | undefined {
  return posts.find((p) => p.slug === slug);
}

export function formatDate(iso: string): string {
  return new Date(`${iso}T00:00:00`).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}
